import 'package:travel_wiki/country_model.dart';

class Btn {
  static final List<Country> countries = [
    Country("Argentina", "lib/images/argentina.png",
        "Argentina is a diverse destination known for its rich culture, vibrant cities, and breathtaking landscapes. Travelers can explore the bustling streets of Buenos Aires, visit the iconic Iguazu Falls, or indulge in the country's renowned beef cuisine. It's essential to be aware of the varying climates across regions, with Patagonia offering different experiences than the northern regions. Spanish is the official language, and understanding basic phrases can enhance the travel experience."),
    Country("Australia", "lib/images/australia.png",
        "Australia, famous for its unique wildlife and vast landscapes, offers a mix of urban and natural attractions. Sydney's Opera House and the Great Barrier Reef are must-visit landmarks. Travelers should be prepared for diverse climates, from tropical in the north to temperate in the south. English is the official language, and local customs, including beach etiquette and wildlife safety, should be respected."),
    Country("Austria", "lib/images/austria.png",
        "Austria is a picturesque country known for its classical music heritage, stunning alpine scenery, and charming cities like Vienna and Salzburg. Visitors can enjoy cultural events, ski resorts, and historic architecture. German is the official language, and knowing a few phrases can be helpful. Tipping is customary, and public transportation is efficient for exploring the country."),
    Country("Brazil", "lib/images/brazil.png",
        "Brazil is a vibrant destination with diverse landscapes, from the Amazon rainforest to the sandy beaches of Rio de Janeiro. Portuguese is the official language, and learning basic phrases can enhance interactions. Travelers should be aware of safety precautions in urban areas and be prepared for a lively carnival culture."),
    Country("Canada", "lib/images/canada.png",
        "Canada is known for its friendly locals, stunning natural beauty, and diverse cities. From the cosmopolitan Toronto to the picturesque Banff National Park, there's something for everyone. English and French are official languages, and understanding the local customs, especially in Indigenous communities, is important."),
    Country("China", "lib/images/china.png",
        "China offers a blend of ancient traditions and modern marvels. Visitors can explore the Great Wall, experience traditional tea ceremonies, and marvel at futuristic cityscapes. Mandarin is the official language, and understanding cultural norms, such as respecting elders, is crucial. Travelers should be aware of regional variations in cuisine and customs."),
    Country("Cyprus", "lib/images/cyprus.png",
        "Cyprus is a Mediterranean gem with a rich history and beautiful beaches. English and Greek are widely spoken, making communication easy. Travelers should explore archaeological sites, enjoy local cuisine, and be mindful of the island's divided status."),
    Country("Egypt", "lib/images/egypt.png",
        "Egypt is a land of ancient wonders, including the pyramids and Sphinx. Visitors should be prepared for hot temperatures, especially in the desert regions. Arabic is the official language, and understanding local customs and respecting Islamic traditions is important."),
    Country("France", "lib/images/france.png",
        "France is synonymous with romance, art, and culinary excellence. From the iconic Eiffel Tower in Paris to the vineyards of Bordeaux, there's much to explore. French is the official language, and basic phrases can enhance the experience. Tipping is included in restaurant bills, and courtesy in social interactions is valued."),
    Country("Germany", "lib/images/germany.png",
        "Germany offers a mix of historic charm and modern innovation. Visitors can explore castles along the Rhine, attend Oktoberfest in Munich, or experience Berlin's vibrant culture. German is the official language, and understanding the efficient public transportation system enhances travel. Cash is widely used, and credit cards may not be accepted everywhere."),
    Country("Greece", "lib/images/greece.png",
        "Greece is a haven of ancient history, beautiful islands, and Mediterranean cuisine. Visitors should explore Athens' historical sites, relax on the beaches of Santorini, and savor local delicacies. Greek is the official language, and being aware of social customs, like the importance of family, enriches the experience."),
    Country("India", "lib/images/india.png",
        "India is a diverse and colorful destination with a rich tapestry of cultures, landscapes, and traditions. From the Taj Mahal in Agra to the vibrant markets of Delhi, there's much to explore. English is widely spoken, and understanding cultural diversity is crucial. Travelers should be prepared for varying climates and be mindful of local customs and traditions."),
    Country("Ireland", "lib/images/ireland.png",
        "Ireland is known for its lush landscapes, friendly locals, and vibrant cities. Visitors can explore ancient castles, enjoy traditional music in pubs, and marvel at the Cliffs of Moher. English and Irish are official languages, and adapting to the casual and friendly Irish way of life enhances the experience."),
    Country("Israel", "lib/images/israel.png",
        "Israel offers a blend of ancient history, religious significance, and modern innovation. Visitors should explore Jerusalem's Old City, relax by the Dead Sea, and savor the diverse cuisine. Hebrew and Arabic are official languages, and respecting religious customs is important."),
    Country("Italy", "lib/images/italy.png",
        "Italy is a treasure trove of art, history, and culinary delights. From the ancient ruins of Rome to the romantic canals of Venice, there's something for every traveler. Italian is the official language, and understanding local customs, like the importance of food in social gatherings, is essential."),
    Country("Japan", "lib/images/japan.png",
        "Japan seamlessly combines tradition and modernity. Visitors can experience ancient temples in Kyoto, futuristic technology in Tokyo, and serene landscapes in Hiroshima. Japanese is the official language, and politeness and respect are integral to the culture. Understanding traditions like tea ceremonies and onsen etiquette enhances the travel experience."),
    Country("Mexico", "lib/images/mexico.png",
        "Mexico boasts a rich cultural heritage, from ancient Mayan ruins to lively mariachi music. Visitors should explore the historic center of Mexico City, relax on the beaches of Cancun, and savor authentic street food. Spanish is the official language, and embracing the vibrant and festive atmosphere is key."),
    Country("Morocco", "lib/images/morocco.png",
        "Morocco offers a tapestry of vibrant markets, historic cities, and diverse landscapes. Visitors should explore the medinas of Marrakech, experience the Sahara Desert, and savor Moroccan cuisine. Arabic and Berber are widely spoken, and understanding the local bargaining culture is helpful."),
    Country("Netherlands", "lib/images/netherlands.png",
        "The Netherlands is known for its picturesque canals, tulip fields, and vibrant cities. Visitors should explore Amsterdam's museums, cycle through the countryside, and embrace the relaxed Dutch lifestyle. Dutch and English are widely spoken, and politeness is highly valued."),
    Country("New_Zealand", "lib/images/new_zealand.png",
        "New Zealand is a haven for outdoor enthusiasts, with stunning landscapes and Maori cultural experiences. Visitors can explore the geothermal wonders of Rotorua, hike in Fiordland National Park, and enjoy outdoor activities. English and Maori are official languages, and respecting the indigenous culture is important."),
    Country("Norway", "lib/images/norway.png",
        "Norway's dramatic fjords, vibrant cities, and Northern Lights make it a unique destination. Visitors should explore Oslo's museums, take a scenic train journey, and experience the outdoor beauty. Norwegian and English are widely spoken, and embracing the concept of 'friluftsliv' (outdoor living) is recommended."),
    Country("Peru", "lib/images/peru.png",
        "Peru is a land of ancient civilizations, including the iconic Machu Picchu. Visitors should explore the Inca Trail, experience the cultural heritage of Cusco, and savor Peruvian cuisine. Spanish and Quechua are spoken, and adapting to the high-altitude conditions is important."),
    Country("Singapore", "lib/images/singapore.png",
        "Singapore is a modern metropolis known for its cleanliness, diverse cuisine, and futuristic architecture. Visitors should explore the Gardens by the Bay, experience the vibrant street food scene in hawker centers, and appreciate the cultural diversity in neighborhoods like Little India and Chinatown. English is widely spoken, and the efficient public transportation system makes it easy to navigate the city-state."),
    Country("South_Africa", "lib/images/south_africa.png",
        "South Africa offers a diverse landscape, from wildlife-rich safaris to vibrant cities. Visitors should explore Kruger National Park, experience the multicultural atmosphere in Cape Town, and learn about the country's complex history. English is widely spoken, and understanding the cultural diversity, including the importance of tribal traditions, enhances the experience."),
    Country("South_Korea", "lib/images/south_korea.png",
        "South Korea seamlessly blends ancient traditions with modern innovation. Visitors can explore historic palaces in Seoul, relax in traditional tea houses, and indulge in Korean barbecue. Korean is the official language, and respecting social hierarchies and customs, such as removing shoes indoors, is important."),
    Country("Spain", "lib/images/spain.png",
        "Spain is a country of lively fiestas, historic landmarks, and diverse landscapes. From the beaches of Barcelona to the historic streets of Madrid, there's much to explore. Spanish is the official language, and embracing the local custom of the siesta and enjoying tapas culture enhances the travel experience."),
    Country("Switzerland", "lib/images/switzerland.png",
        "Switzerland is a haven for nature lovers and outdoor enthusiasts. Visitors can explore the Swiss Alps, cruise on pristine lakes, and experience the efficiency of Swiss cities like Zurich and Geneva. German, French, Italian, and Romansh are official languages, and understanding the punctuality and precision of Swiss culture is important."),
    Country("Thailand", "lib/images/thailand.png",
        "Thailand is a tropical paradise known for its stunning beaches, vibrant markets, and rich cultural heritage. Visitors should explore the temples of Bangkok, relax on the islands of Phuket or Koh Phi Phi, and savor Thai cuisine. Thai is the official language, and respecting local customs, such as removing shoes before entering homes and temples, is important."),
    Country("Tunisa", "lib/images/tunisa.png",
        "Tunisia offers a mix of ancient history, Mediterranean beaches, and vibrant markets. Visitors should explore the ruins of Carthage, experience the desert landscapes of the Sahara, and savor Tunisian cuisine. Arabic and French are widely spoken, and understanding the bargaining culture in markets is useful."),
    Country("UAE", "lib/images/uae.png",
        "The United Arab Emirates (UAE) is a modern and luxurious destination known for its skyscrapers, desert adventures, and shopping extravaganzas. Visitors should explore the futuristic city of Dubai, experience the cultural heritage in Abu Dhabi, and indulge in luxury experiences. Arabic is the official language, and respecting Islamic traditions, including dress code in public places, is important."),
    Country("UK", "lib/images/uk.png",
        "The United Kingdom (UK) is a blend of historic charm and contemporary culture. Visitors should explore the iconic landmarks of London, experience the cultural richness of Edinburgh, and enjoy the picturesque landscapes of the British countryside. English is the official language, and understanding the diversity of the UK's regions adds depth to the travel experience."),
    Country("USA", "lib/images/usa.png",
        "The United States is a vast and diverse destination with iconic landmarks, natural wonders, and vibrant cities. Visitors can explore the Grand Canyon, experience the cultural melting pot of New York City, and relax on the beaches of Hawaii. English is the primary language, and understanding regional differences in cuisine, customs, and accents enhances the travel experience. Travelers should also be aware of entry requirements and transportation options due to the country's size and diversity."),
  ];
}
